
//#define SCRIPT_DEBUG
#pragma once

#include "HullOS.h"
extern struct LanguageHandler PythonIshLanguage;

int pythonIshdecodeScriptLine(char *input);
void pythonIshShowPrompt();

#define COMMAND_ANGRY 0
#define COMMAND_HAPPY 1
#define COMMAND_MOVE 2
#define COMMAND_TURN 3
#define COMMAND_ARC 4
#define COMMAND_DELAY 5
#define COMMAND_COLOUR 6
#define COMMAND_COLOR 7
#define COMMAND_PIXEL 8
#define COMMAND_SET 9
#define COMMAND_IF 10
#define COMMAND_DO 11
#define COMMAND_WHILE 12
#define COMMAND_INTIME 13
#define COMMAND_ENDIF 14
#define COMMAND_FOREVER 15
#define COMMAND_ENDWHILE 16
#define COMMAND_SOUND 17
#define COMMAND_UNTIL 18
#define COMMAND_CLEAR 19
#define COMMAND_RUN 20
#define COMMAND_BACKGROUND 21
#define COMMAND_ELSE 22
#define COMMAND_RED 23
#define COMMAND_GREEN 24
#define COMMAND_BLUE 25
#define COMMAND_YELLOW 26
#define COMMAND_MAGENTA 27
#define COMMAND_CYAN 28
#define COMMAND_WHITE 29
#define COMMAND_BLACK 30
#define COMMAND_WAIT 31
#define COMMAND_STOP 32
#define COMMAND_BEGIN 33
#define COMMAND_END 34
#define COMMAND_PRINT 35
#define COMMAND_PRINTLN 36
#define COMMAND_BREAK 37
#define COMMAND_DURATION 38
#define COMMAND_CONTINUE 39
#define COMMAND_ANGLE 40
#define COMMAND_SAVE 41
#define COMMAND_LOAD 42
#define COMMAND_DUMP 43
#define COMMAND_CHAIN 44
#define COMMAND_SEND 45
#define COMMAND_NO_WAIT 46
#define COMMAND_FILES 47
#define COMMAND_DELETE 48


