#pragma once

#include "HullOS.h"

extern struct LanguageHandler RockstarLanguage;

void rockstarShowPrompt();


#define ROCKSTAR_COMMAND_ANGRY 0
#define ROCKSTAR_COMMAND_HAPPY 1
#define ROCKSTAR_COMMAND_MOVE 2
#define ROCKSTAR_COMMAND_TURN 3
#define ROCKSTAR_COMMAND_ARC 4
#define ROCKSTAR_COMMAND_DELAY 5
#define ROCKSTAR_COMMAND_COLOUR 6
#define ROCKSTAR_COMMAND_COLOR 7
#define ROCKSTAR_COMMAND_PIXEL 8
#define ROCKSTAR_COMMAND_SET 9
#define ROCKSTAR_COMMAND_IF 10
#define ROCKSTAR_COMMAND_DO 11
#define ROCKSTAR_COMMAND_WHILE 12
#define ROCKSTAR_COMMAND_INTIME 13
#define ROCKSTAR_COMMAND_ENDIF 14
#define ROCKSTAR_COMMAND_FOREVER 15
#define ROCKSTAR_COMMAND_ENDWHILE 16
#define ROCKSTAR_COMMAND_SOUND 17
#define ROCKSTAR_COMMAND_UNTIL 18
#define ROCKSTAR_COMMAND_CLEAR 19
#define ROCKSTAR_COMMAND_RUN 20
#define ROCKSTAR_COMMAND_BACKGROUND 21
#define ROCKSTAR_COMMAND_ELSE 22
#define ROCKSTAR_COMMAND_RED 23
#define ROCKSTAR_COMMAND_GREEN 24
#define ROCKSTAR_COMMAND_BLUE 25
#define ROCKSTAR_COMMAND_YELLOW 26
#define ROCKSTAR_COMMAND_MAGENTA 27
#define ROCKSTAR_COMMAND_CYAN 28
#define ROCKSTAR_COMMAND_WHITE 29
#define ROCKSTAR_COMMAND_BLACK 30
#define ROCKSTAR_COMMAND_NO_WAIT 31
#define ROCKSTAR_COMMAND_STOP 32
#define ROCKSTAR_COMMAND_BEGIN 33
#define ROCKSTAR_COMMAND_END 34
#define ROCKSTAR_COMMAND_PRINT 35
#define ROCKSTAR_COMMAND_PRINTLN 36
#define ROCKSTAR_COMMAND_BREAK 37
#define ROCKSTAR_COMMAND_DURATION 38
#define ROCKSTAR_COMMAND_CONTINUE 39
#define ROCKSTAR_COMMAND_ANGLE 40
#define ROCKSTAR_COMMAND_SAVE 41
#define ROCKSTAR_COMMAND_LOAD 42
#define ROCKSTAR_COMMAND_DUMP 43
#define ROCKSTAR_COMMAND_DANCE 44
#define ROCKSTAR_COMMON_VARIABLE 45
#define ROCKSTAR_IS_OPERATOR 46
